FROM node:22.12.0-alpine as builder

WORKDIR /build

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm install

COPY ..

RUN npm run build

FROM node:22.12.0-alpine as runtime

WORKDIR /app

COPY --from=builder /build/node_modules node_modules
COPY --from=builder /build/package.json package.json
COPY --from=builder /build/package-lock.json package-lock.json
COPY --from=builder /build/main.js main.js

CMD ["npm", "start"]

EXPOSE 3000

# docker build -t my-nodejs-app . // . means file exist in this folder only (image build)
# docker run -d -p 3000:3000 --name my-nodejs-app my-nodejs-app // to run this image
# docker exec -it my-nodejs-app bash // to get into the container